spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    #type: com.zaxxer.hikari.HikariDataSource默认配置
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-wait: -1
        max-idle: 8
        min-idle: 0
  mvc:
    servlet:
      path: /tmall

  thymeleaf:
    encoding: UTF-8
    cache: false
    mode: LEGACYHTML5
    servlet:
      content-type: text/html

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB



